
spring:
  data:
    mongodb:
      database: Project2
      port: 27017
  application:
    name: product-application

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8070